- name: Check Tomcat9 Sample
  hosts: all
  gather_facts: true
  tasks:
    - name: Check Tomcat
      service_facts:
        pattern: tomcat9.service
    - name: Tomcat Status
      debug:
        var: ansible_facts.services['tomcat9.service'].state
