- name: Check service status
  hosts: all
  gather_facts: no
  vars:
    SERVICE: tomcat9.service
  tasks:
    - name: Service Facts
      service_facts:

    - debug:
        msg: "{{ services[SERVICE]['status'] }}"
