---
- name: Executar Get-Website
  hosts: all
  gather_facts: no
  tasks:
    - name: Executar Get-Website
      win_shell: $sites = Get-Website | Format-Table -AutoSize | Out-String
      Write-Output $sites
      register: resultado

    - name: Exibir Resultado
      debug:
        var: resultado.stdout_lines
