---
- name: Executar Get-Website
  hosts: all
  gather_facts: no
  tasks:
    - name: Executar Get-Website
      win_shell: $result = cmd.exe /c "%windir%\system32\inetsrv\appcmd.exe list app"; foreach($line in $($result -split "`r`n")) { $array = $line.Split('"'); Write-Output $array[1] }
      register: resultado

    - name: Exibir Resultado
      debug:
        var: resultado.stdout_lines
