---
- name: Executar Get-Website
  hosts: all
  gather_facts: no
  tasks:
    - name: Executar Get-Website
      win_shell: |
        cmd.exe /c "%windir%\system32\inetsrv\appcmd.exe list app"
        echo teste
      register: resultado

    - name: Exibir Resultado
      debug:
        var: resultado.stdout_lines
